### ISSUE TITLE
语音助手能否直接把内容传递给ha使用？[建议]

### ISSUE THREAD

**Issue by SamuelReeves** [nesror/SmartHouse#9]
在用smarthouse感觉真的是不错好用，手机上可以直接划出语音助手来控制也非常方便，最近想起来，是不是可以功能更上一层楼呢？比如我手机上看到一个好的视频链接或者公众号文章想要保持下载下来，复制了资源链接，直接划出语音助手，发给ha，ha里提前设置了判断，判断是什么内容后让ha中转一下把内容发送到对应的工具里完成自动化下载。但是我看了下好像发过去的内容没有直接在哪个实体的属性里，好像用不了，不知道有没有可能完成这个功能呢？就是一个想法，感觉如果可以这样做的话，提早在ha里把自己的需求都设置好，就可以成为非常全能的助理了。

**Comment by nesror** [comment]
参考下面的
```
  alias: "语音助手输入123就开灯"
  description: ""
  trigger:
    - platform: conversation
      command: "123"
  condition: []
  action:
    - service: light.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: light.yeelight_ceil26_0x158027b8
  mode: single

```
